---
title: "TEORIA MONETÁRIA MODERNA"
subtitle: "uma crítica ao mainstream"
author: Alberson Miranda
date: '`r format(Sys.Date(), "%B de %Y")`'
navigation: horizontal
format:
    beamer:
        theme: "Madrid"
        include-in-header: config/preamble_apresentacao.tex
        output-file: render/apresentacao.pdf
        toc: true
        toc-title: SUMÁRIO
execute:
    echo: false
cite-method: biblatex
incremental: true
---

### OBJETIVO

Apresentar as críticas da Teoria Monetária Moderna (MMT) ao *mainstream* e explicitar sua aproximação à corrente keynesiana

# TEORIA DA MOEDA WALRASIANA

## EQUILÍBRIO GERAL

- Seção VI: Teoria da Circulação e da Moeda \cite{walras_leon_compendio_1986}
- Famílias e empresas conhecem a todo momento os preços de compra e venda de produtos e, consequentemente, suas necessidades de demanda por moeda, formando um equilíbrio geral analítico
- Contínua perturbação e restabelecimento do equilíbrio através do mecanismo de livre concorrência

---

### INFLAÇÃO

"Todo aumento ou diminuição na quantidade da mercadoria-moeda tem como efeito um aumento ou diminuição sensivelmente proporcional nos preços"

## MOEDA-MERCADORIA

- A moeda é uma mercadoria e seu preço varia de acordo com sua raridade, da mesma forma que qualquer outra mercadoria
- Instrumental: "a necessidade que se tem de moeda não passa da necessidade que se tem das mercadorias que podem ser compradas com essa moeda"
- Teoria dos Fundos de Empréstimo: I = S. É necessária poupança prévia ao investimento

# TEORIA DA MOEDA KEYNESIANA

## MOEDA COMO FATO SOCIAL

- Cap. 21: A Teoria dos Preços \cite{keynes_teoria_2017}
- "A agudeza e as peculiaridades de nossos problemas contemporâneos emanam, portanto, do fato de que a taxa média de juros compatível com um volume médio razoável de emprego pode ser inaceitável para os possuidores de riqueza, de forma que seja impossível estabelecê-la facilmente por meio de simples manipulações da quantidade de dinheiro"

## REFUTAÇÃO DA TEORIA DOS FUNDOS DE EMPRÉSTIMO

- Tanto o volume dos fundos disponíveis como a taxa de juros são determinados pela oferta de crédito, que por sua vez é criada pelo Estado e pelo sistema bancário e não é restrita pela poupança
- A oferta de crédito é determinada de forma endógena pelo sistema bancário de acordo com as expectativas \cite{resende_camisa_2022}

# PRINCÍPIOS DA MMT

## O QUE HÁ DE MODERNO NA MMT?

Argumentação sob a ótica da contabilidade social contemporânea (ex.: transações entre Tesouro e Banco Central)

## O QUE HÁ DE MODERNO NA MMT?

- *The sovereign government cannot become insolvent in its own currency; it can always make all payments as they come due in its own currency* \cite{wray_modern_2015}

- Não inclui estados e municípios
- Exclui nações da zona do Euro

---

### 1ª CONCLUSÃO

Um Estado soberano não requer tributação prévia para gastar. Pelo contrário, precisa gastar antes para que os agentes possam pagar seus tributos.

## O QUE HÁ DE MODERNO NA MMT?

- *Sovereign government does not need to "borrow" its currency in order to spend* \cite{wray_modern_2015}
- A comercialização de títulos é a operacionalização da política monetária, com objetivo de alcançar uma determinada taxa de juro

## O QUE HÁ DE MODERNO NA MMT?

- Princípio das partidas dobradas: todo ativo tem um passivo correspondente
- Um título de dívida é um passivo do Estado e um ativo para famílias e firmas
- Reduzir a dívida pública significa diminuir sua contrapartida nas famílias e firmas

---

### 2ª CONCLUSÃO

Uma política de orçamento equilibrado significa que não há contribuição líquida do Estado na economia e não há qualquer razão para se buscar tal objetivo

## O QUE HÁ DE MODERNO NA MMT?

- Numa economia com 2 setores, governo e privado, o déficit do governo é o superávit do setor privado
- Se o governo opera em superávit contínuo, ou seja, $T > G$, então o setor privado tem queda em sua riqueza financeira líquida

# REFERÊNCIAS
