---
title: "TEORIA MONETÁRIA MODERNA"
subtitle: "Aspectos keynesianos e algumas críticas ao mainstream"
author: "Alberson da Silva Miranda"
date: "`r format(Sys.Date(), '%B de %Y')`"
format:
    pdf:
        include-in-header: config/preamble.tex
        keep-tex: false
        output-file: render/artigo_II.pdf
cite-method: biblatex
suppress-bibliography: true
fontsize: 12pt
geometry: margin=1in
number-sections: true
crossref:
  fig-prefix: "Figura"
  tab-prefix: "Tabela"
  eq-prefix: ""
---

# INTRODUÇÃO {-}

A política monetária tem ocupado espaço no debate econômico, inclusive a nível popular

# ECONOMIA MONETÁRIA NO MAINSTREAM

Dois dos pilares teóricos da economia do *mainstream* são o equilíbrio e a racionalidade dos agentes. Para que o mecanismo concorrencial seja também um mecanismo de convergência para o equilíbrio, os agentes econômicos devem saber, a qualquer instante dado, os preços de todo bem ou serviço. Além disso, também
são hipóteses necessárias o conhecimento de:

\begin{citacao}
1) que provisões em produtos deve ter para sua comodidade; 2) quanto deve ter em caixa para restabelecer essas provisões e para comprar produtos e serviços consumíveis, à medida que são consumidos (esperando que esgotem os prazos de seus arrendamentos, de seus dalários e de seus juros), quer para comprar capitais novos. \cite{walras_leon_compendio_1986}
\end{citacao}

Nesse sentido, "a necessidade que se tem de moeda não passa da necessidade que se tem das mercadorias que podem ser compradas com essa moeda". A moeda é uma mercadoria e seu preço varia de acordo com sua raridade, da mesma forma que qualquer outra mercadoria. Assim, o mercado monetário também está sujeito ao mecanismo concorrencial e é dotado de equilíbrio analítico, ou seja, pode ser conhecido, calculado e tem solução única. Excessos ou deficiência de moeda são apenas distúrbios momentâneos, com o equilíbrio do mercado sendo restabelecido via livre concorrência.

O valor da moeda é determinado a partir da equivalência entre a quantidade de mercadorias em circulação e a quantidade de moeda necessária para comprá-las. Assim, menor quantidade de moeda deve resultar em menores preços (e maior quantidade de moeda deve resultar em maior nível de preços) para manter a equivalência. Nas palavras de \textcite{walras_leon_compendio_1986}, "Todo aumento ou diminuição na quantidade da mercadoria-moeda tem como efeito um aumento ou diminuição sensivelmente proporcional nos preços", ou seja, os movimentos inflacionários e deflacionários se dão pela relação entre a raridade da mercadoria-moeda e da raridade das mercadorias em circulação.

Esse caráter instrumental da moeda tem algumas implicações. Primeiramente, a taxa de juros é endógena. Será definida pelas transações no mercado monetário enquanto busca a quantidade de moeda de equilíbrio. O controle da autoridade monetária se dá pelo controle quantidade de moeda e a taxa de juros é uma consequência do equilíbrio de mercado.

Em segundo lugar, um nível de emprego que signifique quantidade de moeda acima do nível de equilíbrio irá, necessariamente, causar inflação na mesma proporção do aumento da moeda, de forma a anular esse excesso. Portanto, algum nível de pobreza e desemprego é justificado e necessário em nome da estabilidade monetária (Curva de Phillips).

Outra conclusão de fundamental importância é a Teoria dos Fundos de Empréstimos. Como o aumento da massa monetária acima do nível de equilíbrio não afeta a renda real, a política monetária é neutra. Assim, o investimento requer poupança prévia: $I=S$.

# REFERÊNCIAS {-}